#!/usr/bin/env python3
# coding: utf-8

import os
import re
import sys
import glob
import argparse


orca = {
  "conv_error_str": "NOT FULLY CONVERGED",
  "multijob_pos": 3,
  "multijob_str": "JOBS TO BE PROCESSED THIS RUN",
  "out_file": "orca",
  "scf_str": "SCF CONVERGED AFTER"
}

qchem = {
  "conv_error_str": "False",
  "multijob_pos": -1,
  "multijob_str": "^User input: \d of \d*$",
  "out_file": "job.out",
  "scf_str": "Convergence criterion met"
}


def initArgparser():
  parser = argparse.ArgumentParser(
      description='Check all ORCA files for successful run.')
  parser.add_argument("-v", '--verbose', nargs='?', const=0, type=int,
                      help="Print more. Number of rows optional. 0 prints everything")
  return parser.parse_args()


def handleFile(prog, file):
  # init variables
  failed = []
  count_criter = 0
  num_jobs = 1

  with open(file) as f:
    for line in f:
      # get number of jobs in multijob file
      if re.match(prog["multijob_str"], line.strip()):
        pos = prog["multijob_pos"]
        num_jobs = int(line.strip().split()[pos])
        continue

      if prog["scf_str"] in line:
        count_criter += 1
        continue

      if prog["conv_error_str"] in line:
        failed.append(file)
        break  

    # check convergence for multijob
    if count_criter != num_jobs:
      failed.append(file)

  return failed


def main():
  args = initArgparser()

  # compile filelist
  filelist = getFileList()
  print(f"Going to check {len(filelist)} files...")

  # iterate filelist
  for i, filename in enumerate(filelist):
    # ORCA files
    if orca["out_file"] in filename:
      failed = handleFile(orca, filename)

    # Q-CHEM files
    elif qchem["out_file"] in filename:
      failed = handleFile(qchem, filename)

    # unrecognized files
    else:
      print(f"File '{filename}' not recognized.")

    # pretty progress bar
    progress(i+1, len(filelist))


  print("\nFinished!\n")
  if len(failed) == 0:
    print("All jobs successful!!")
  else:
    print("WARNING!!! Convergence not reached in:")
    for i in failed:
      print(i)
  

def getFileList():
  filelist = []

  print("Compiling file list...")
  for file in glob.glob('./**/orca*.out', recursive=True):
    filelist.append(file)

  for file in glob.glob('./**/job.out', recursive=True):
    filelist.append(file)

  if len(filelist) == 0:
    sys.exit("No '.out' files found.")

  return filelist


def progress(count, total, status=''):
  bar_len = 60
  filled_len = int(round(bar_len * count / float(total)))

  percents = round(100.0 * count / float(total), 1)
  bar = '=' * filled_len + '-' * (bar_len - filled_len)

  sys.stdout.write('[%s] %s%s %s\r' % (bar, percents, '%', status))
  sys.stdout.flush()


if __name__ == '__main__':
  main()
