#!/usr/bin/env python3
# coding: utf-8

import argparse


def get_energy(outputfile):
    '''return final occurence as numpy float

    match the pattern below
    -------------------------   --------------------
    FINAL SINGLE POINT ENERGY     -2853.942547180734
    -------------------------   --------------------'''

    with open(outputfile) as f:
        for line in f:
            if 'FINAL SINGLE POINT ENERGY' in line:
                l = line.split()
                e = l[-1]

    e = float(e)

    return e


def run():
    'run from command line'
    parser = argparse.ArgumentParser(description='Prints final occurence of FINAL SINGLE POINT ENERGY from orca output file')
    parser.add_argument('orca_output', help='output file of orca calculation')
    args = parser.parse_args()
    
    out = args.orca_output
    e = get_energy(out)
    print(e)


if __name__ == '__main__':
    run()
